local _, ns = ...

-- Bestiary settings and help content; shared page frames live in FieldbookShell.
function ns.CreateBestiaryPages(journal,shell,book,callbacks)
    local ui=ns.FieldbookUI
    local label,button,edit=ui.Label,ui.Button,ui.Edit
    local function createBookPage(...) return shell:CreatePage(...) end
    local function showBookPage(page) shell:ShowPage(page) end
    local eventLog,eventBody=createBookPage("AzerothFieldbookEventLog","Event log",65)
    book.eventLog=eventLog
    local eventPage=0
    local eventText=label(eventBody,"",30,0,530,"GameFontHighlightSmall")
    local eventStatus=label(eventLog,"",255,-722,300,"GameFontHighlightSmall")
    local newer,older
    local function refreshEventLog()
        local log=journal:GetEventLog()
        local entries=log.entries
        eventPage=math.max(0,math.min(eventPage,math.max(0,math.ceil(#entries/50)-1)))
        local lines={}
        for index=#entries-eventPage*50,math.max(1,#entries-eventPage*50-49),-1 do
            local entry=entries[index]
            local stamp=entry.timestamp and date and date("%Y-%m-%d %H:%M:%S",entry.timestamp) or "Unknown time"
            lines[#lines+1]="|cff999999"..stamp.."|r\n"..entry.message
        end
        eventText:SetText(#lines>0 and table.concat(lines,"\n\n") or "No events recorded yet. Events are saved even when chat messages are disabled.")
        local contentHeight=math.max(1,eventText:GetStringHeight()+20)
        local height=math.max(200,math.min(767,eventLog.contentTop+contentHeight+65))
        local resized=eventLog:GetHeight()~=height
        eventLog:SetHeight(height)
        eventBody:SetHeight(contentHeight)
        local range=math.max(0,contentHeight-(height-eventLog.contentTop-65))
        eventLog.scroll:SetVerticalScroll(math.min(eventLog.scroll:GetVerticalScroll() or 0,range))
        eventLog.scroll:UpdateScrollChildRect()
        local bar=eventLog.scroll.ScrollBar
        if bar and type(bar)~="function" then bar:SetShown(range>0) end
        eventLog.scroll:EnableMouseWheel(range>0)
        if resized and eventLog:IsShown() and ns.WindowPositions then ns.WindowPositions:AvoidWindowOverlap(eventLog) end
        eventStatus:SetText(#entries.." events"..(#entries>50 and (" · Page "..(eventPage+1).." / "..math.ceil(#entries/50)) or ""))
        newer:SetShown(#entries>50);older:SetShown(#entries>50)
        newer:SetEnabled(eventPage>0);older:SetEnabled((eventPage+1)*50<#entries)
    end
    newer=button(eventLog,"Newer",30,-722,100,function() eventPage=eventPage-1;eventLog.scroll:SetVerticalScroll(0);refreshEventLog() end)
    older=button(eventLog,"Older",140,-722,100,function() eventPage=eventPage+1;eventLog.scroll:SetVerticalScroll(0);refreshEventLog() end)
    newer:ClearAllPoints();newer:SetPoint("BOTTOMLEFT",30,21)
    older:ClearAllPoints();older:SetPoint("BOTTOMLEFT",140,21)
    eventStatus:ClearAllPoints();eventStatus:SetPoint("BOTTOMRIGHT",-35,28)
    eventLog.text,eventLog.newer,eventLog.older=eventText,newer,older
    eventLog:SetScript("OnShow",refreshEventLog)
    journal:SetEventLogChangedCallback(function() if eventLog:IsShown() then refreshEventLog() end end)
    eventLog:Hide()
    local help,helpBody=createBookPage("AzerothFieldbookHelp","AZEROTH FIELDBOOK - HELP",24)
    local helpInstructions=label(helpBody,"|cffffd1001. Encounter|r\nTarget or mouse over an attackable NPC to add it to your Bestiary. Its name, creature type, location and observed level range are recorded automatically.\n\n|cffffd1002. Record|r\nCasts with readable spell IDs are automatically confirmed, including in combat, with a blue [A]. Readable buffs are also recorded outside combat; their caster may be unknown. Turn automatic recording off under Options > Ability recording. Name-only casts and safe post-combat imports remain pending notes. Display-only restricted IDs cannot be saved. Abilities the addon cannot observe directly can also be added manually. Damage ranges must be recorded manually from your own data. Equal-level observations are recommended so level scaling does not distort the results.\n\n|cffffd1003. Review|r\nOpen the Bestiary and select a creature to review its observations. Confirm accurate abilities, reject doubtful ones, or remove notes you no longer want.\n\n|cffffd1004. Lock Entry|r\nWhen you are satisfied with an entry, lock it to stop further changes. Confirmed abilities appear in NPC tooltips. You continue to earn knowledge from kills and discoveries, and ID Logs, Notes and received Rumours remain separate and editable. Unlock to resume recording and hide its abilities from tooltips.\n\n|cffffd1005. Browse|r\nUse creature-type filters and search to navigate the Bestiary. Click Index to reveal the A-Z tabs; click it again to hide them and clear the letter filter. Account-wide tracking is on by default in Options. Turn it off to use this character's separate journal; changes apply after /reload. Existing character journals merge once when first using account tracking.\n\n|cffffd1006. Share|r\nOutside combat, Share sends one creature to one named recipient. New basics cost 1 knowledge; already-known basics are free. Each selected rumour costs 1 knowledge. Choose any number of existing traits within the report size limit. All received traits are unverified Rumours with the offering character's name. Click Rumours in the creature header to open or close its separate window. The green tick verifies a rumour and adds it to your journal; x rejects it. Unlock an entry before verifying. Matching manual records remove rumours, and repeated rejected claims are marked Previously rejected. Receiving alone never confirms traits or abilities; verified abilities use the normal entry-lock and tooltip rules.\n\nThe book shows knowledge earned. Share shows available knowledge after spending and reservations. Send reserves the maximum cost; acceptance waives the basic-information cost if the recipient already knows it and commits the final cost. Declines and pre-commit cancellation are free. Unknown delivery keeps the cost spent: reopen Share to retry the same report, at most three times within 24 hours. Receiving earns no knowledge; later personal discovery still can. Entry deletion preserves credited milestones and spending; full reset erases them.",35,0,535)
    local pointsBlock=CreateFrame("Frame",nil,helpBody,"BackdropTemplate")
    pointsBlock:SetPoint("TOPLEFT",helpInstructions,"BOTTOMLEFT",0,-18)
    pointsBlock:SetWidth(535)
    pointsBlock:SetBackdrop({bgFile="Interface\\Buttons\\WHITE8X8",edgeFile="Interface\\Tooltips\\UI-Tooltip-Border",edgeSize=12,insets={left=3,right=3,top=3,bottom=3}})
    pointsBlock:SetBackdropColor(0.12,0.08,0.03,0.35)
    pointsBlock:SetBackdropBorderColor(0.55,0.40,0.20,1)
    pointsBlock.title=label(pointsBlock,"Knowledge",14,-14,507,"GameFontNormalLarge")
    pointsBlock.title:SetTextColor(1,0.82,0.14)
    pointsBlock.awardHeading=label(pointsBlock,"Earning knowledge",14,0,507,"GameFontNormal")
    pointsBlock.awardHeading:SetTextColor(1,0.82,0.14)
    pointsBlock.awards=label(pointsBlock,"+1 for new creature discovery\n+1 for new location discovery on an existing creature\n\n+1 for 10 kills\n+2 for 25 kills\n+3 for 50 kills\n\nThe first location is included in a new discovery. New levels are recorded but do not award knowledge.",14,0,507,"GameFontHighlightSmall")
    pointsBlock.spendHeading=label(pointsBlock,"Sharing knowledge",14,0,507,"GameFontNormal")
    pointsBlock.spendHeading:SetTextColor(1,0.82,0.14)
    pointsBlock.spending=label(pointsBlock,"Use knowledge to share creature information with another player.\n\n1 knowledge for basic information; free if the recipient already knows it.\n1 knowledge per selected rumour.\n\nSending reserves the maximum cost; knowledge are spent after acceptance. Receiving information is free.",14,0,507,"GameFontHighlightSmall")
    help.pointsBlock=pointsBlock
    local helpDetails=CreateFrame("Frame",nil,helpBody)
    helpDetails:SetPoint("TOPLEFT",pointsBlock,"BOTTOMLEFT",-35,-18)
    helpDetails:SetWidth(570)
    label(helpDetails,"|cffffd100ABOUT|r",35,0,120,"GameFontNormal")
    local about=label(helpDetails,"Created by |cff40c7ebSpinkler|r\nSPECIAL THANKS to |cfff48cbaErna|r, |cffaad372Labrick|r, and |cffff7c0aRhysdogg|r for beta testing\n\nDeveloped with AI-assisted coding tools.\nDesign, direction, testing and final development decisions by the author.",35,-22,535,"GameFontHighlightSmall")
    help:SetScript("OnShow",function(self)
        local pointsHeight=14
        for i,text in ipairs({pointsBlock.title,pointsBlock.awardHeading,pointsBlock.awards,pointsBlock.spendHeading,pointsBlock.spending}) do
            if i>1 then pointsHeight=pointsHeight+((i==2 or i==4) and 16 or 8) end
            text:ClearAllPoints(); text:SetPoint("TOPLEFT",14,-pointsHeight)
            pointsHeight=pointsHeight+text:GetStringHeight()
        end
        pointsHeight=pointsHeight+14
        pointsBlock:SetHeight(pointsHeight)
        helpDetails:SetHeight(22+about:GetStringHeight())
        helpBody:SetHeight(helpInstructions:GetStringHeight()+18+pointsHeight+18+22+about:GetStringHeight()+16)
        showBookPage(self)
    end)
    help:Hide(); book.help=help
    local options,optionsBody=createBookPage("AzerothFieldbookOptions","AZEROTH FIELDBOOK - OPTIONS",65)
    optionsBody:SetHeight(1230)
    local function optionHeading(title,y)
        local heading=label(optionsBody,title,30,-y,510,"GameFontNormalLarge")
        heading:SetTextColor(1,0.82,0.14)
        local font,size,flags=heading:GetFont()
        if font and type(size)=="number" then heading:SetFont(font,size-2,flags) end
    end
    optionHeading("Tracking",0)
    optionHeading("Chat notifications",122)
    label(optionsBody,"Events are saved in the Event log even when chat messages are off.",35,-216,510,"GameFontHighlightSmall")
    optionHeading("Appearance",266)
    optionHeading("Window behavior",462)
    optionHeading("Sharing",600)
    optionHeading("Tooltips and cast IDs",674)
    optionHeading("Ability recording",1104)
    options.autoRecordBuffs=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.autoRecordBuffs:SetPoint("TOPLEFT",30,-1130);options.autoRecordBuffs:SetSize(24,24)
    label(optionsBody,"Automatically record verified creature abilities",58,-1136,470,"GameFontHighlightSmall")
    label(optionsBody,"Readable cast IDs work in combat; buffs require both you and the creature out of combat. New records get a blue [A] and chat/Event log messages. Fresh evidence restores removed or rejected abilities on unlocked entries; turn off to keep them removed.",35,-1168,510,"GameFontHighlightSmall")
    options.autoRecordBuffs:SetScript("OnClick",function(self)
        journal:SetAutoRecordAbilities(self:GetChecked()==true)
    end)
    options.accountWideTracking=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.accountWideTracking:SetPoint("TOPLEFT",30,-26); options.accountWideTracking:SetSize(24,24)
    label(optionsBody,"Account-wide tracking",58,-32,235,"GameFontHighlightSmall")
    options.trackingReload=label(optionsBody,"",300,-32,235,"GameFontHighlightSmall")
    local function refreshTrackingOption()
        options.accountWideTracking:SetChecked(journal:GetAccountWideTracking())
        options.trackingReload:SetText(journal:IsTrackingChangePending() and "Applies after /reload" or "")
    end
    options.accountWideTracking:SetScript("OnClick",function(self)
        journal:SetAccountWideTracking(self:GetChecked() == true)
        refreshTrackingOption()
    end)
    options.accountWideTracking:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT")
        GameTooltip:SetText("Account-wide tracking")
        GameTooltip:AddLine("Share Bestiary progress across your characters. Turn off to use this character's journal. Changes apply after /reload.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.accountWideTracking:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.autoLockEnabled=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.autoLockEnabled:SetPoint("TOPLEFT",30,-58);options.autoLockEnabled:SetSize(24,24)
    label(optionsBody,"Auto-lock after",58,-64,100,"GameFontHighlightSmall")
    options.autoLockKills=edit(optionsBody,166,-60,45,5)
    options.autoLockKills:SetNumeric(true)
    label(optionsBody,"kills without changes",226,-64,300,"GameFontHighlightSmall")
    options.autoLockEnabled:SetScript("OnClick",function(self)
        journal:SetAutoLockEnabled(self:GetChecked()==true)
        options.autoLockKills:SetEnabled(journal:GetAutoLockEnabled())
    end)
    options.autoLockKills:SetScript("OnEditFocusLost",function(self)
        journal:SetAutoLockKills(self:GetText())
        self:SetText(tostring(journal:GetAutoLockKills()))
    end)
    options.lockNewCritters=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.lockNewCritters:SetPoint("TOPLEFT",30,-90);options.lockNewCritters:SetSize(24,24)
    label(optionsBody,"Lock newly encountered critters",58,-96,470,"GameFontHighlightSmall")
    options.lockNewCritters:SetScript("OnClick",function(self)
        journal:SetLockNewCritters(self:GetChecked()==true)
    end)
    options.lockNewCritters:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT")
        GameTooltip:SetText("Lock newly encountered critters")
        GameTooltip:AddLine("Start new critter entries locked after recording their basic information. Existing entries and manual unlocks are kept. You can unlock a critter to record abilities.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.lockNewCritters:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.creatureAnnouncement=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.creatureAnnouncement:SetPoint("TOPLEFT",30,-148); options.creatureAnnouncement:SetSize(24,24)
    label(optionsBody,"Show a chat message when a new creature entry is added",58,-154,460,"GameFontHighlightSmall")
    options.creatureAnnouncement:SetScript("OnClick",function(self) journal:SetCreatureAnnouncement(self:GetChecked() == true) end)
    options.spellIDTooltips=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.spellIDTooltips:SetPoint("TOPLEFT",30,-732); options.spellIDTooltips:SetSize(24,24)
    label(optionsBody,"Show spell IDs on tooltips if possible",58,-738,460,"GameFontHighlightSmall")
    options.spellIDTooltips:SetScript("OnClick",function(self) journal:SetSpellIDTooltips(self:GetChecked() == true) end)
    options.displayCastIDs=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.displayCastIDs:SetPoint("TOPLEFT",30,-764); options.displayCastIDs:SetSize(24,24)
    label(optionsBody,"Display Cast IDs",58,-770,460,"GameFontHighlightSmall")
    options.displayCastIDs:SetScript("OnClick",function(self) journal:SetDisplayCastIDs(self:GetChecked() == true) end)
    label(optionsBody,"Background brightness",58,-332,170,"GameFontHighlightSmall")
    options.backgroundBrightness=CreateFrame("Slider",nil,optionsBody,"OptionsSliderTemplate")
    options.backgroundBrightness:SetPoint("TOPLEFT",30,-354)
    options.backgroundBrightness:SetSize(180,16)
    local brightnessTrack=options.backgroundBrightness:CreateTexture(nil,"BACKGROUND")
    brightnessTrack:SetPoint("TOPLEFT",2,-4)
    brightnessTrack:SetPoint("BOTTOMRIGHT",-2,4)
    brightnessTrack:SetColorTexture(0.045,0.032,0.018,1)
    options.backgroundBrightness:SetMinMaxValues(0.5,1.5)
    options.backgroundBrightness:SetValueStep(0.05)
    options.backgroundBrightness:SetObeyStepOnDrag(true)
    options.backgroundBrightness:SetScript("OnValueChanged",function(_,value)
        journal:SetBackgroundBrightness(value)
        shell:SetBackgroundBrightness(value)
    end)
    options.killCountTooltips=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.killCountTooltips:SetPoint("TOPLEFT",30,-700);options.killCountTooltips:SetSize(24,24)
    label(optionsBody,"Show kill count in creature tooltips",58,-706,460,"GameFontHighlightSmall")
    options.killCountTooltips:SetScript("OnClick",function(self) journal:SetKillCountTooltips(self:GetChecked()==true) end)
    optionHeading("Spell ID window",814)
    local function windowCheck(key, title, y)
        local check=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
        check:SetPoint("TOPLEFT",30,y); check:SetSize(24,24)
        label(optionsBody,title,58,y-6,470,"GameFontHighlightSmall")
        check:SetScript("OnClick",function(self) journal:SetSpellIDWindowOption(key,self:GetChecked() == true) end)
        options[key]=check
    end
    windowCheck("displaySpellIDWindow","Display Spell ID window",-840)
    windowCheck("spellIDWindowLocked","Lock Spell ID window",-868)
    windowCheck("spellIDWindowIndefinite","Display Spell IDs in the ID window indefinitely",-896)
    windowCheck("displayHoveredAuraSnapshots","Retain hovered aura tooltips",-924)
    windowCheck("spellIDWindowAutoFade","Auto-fade when the Spell ID window contains no data",-952)
    local alphaLabel=label(optionsBody,"Window background opacity: 35%",58,-990,460,"GameFontHighlightSmall")
    options.spellIDWindowAlpha=CreateFrame("Slider",nil,optionsBody,"OptionsSliderTemplate")
    options.spellIDWindowAlpha:SetPoint("TOPLEFT",30,-1010); options.spellIDWindowAlpha:SetSize(180,16)
    local alphaTrack=options.spellIDWindowAlpha:CreateTexture(nil,"BACKGROUND")
    alphaTrack:SetPoint("TOPLEFT",2,-4)
    alphaTrack:SetPoint("BOTTOMRIGHT",-2,4)
    alphaTrack:SetColorTexture(0.045,0.032,0.018,1)
    options.spellIDWindowAlpha:SetMinMaxValues(0,1); options.spellIDWindowAlpha:SetValueStep(0.05)
    options.spellIDWindowAlpha:SetObeyStepOnDrag(true)
    options.spellIDWindowAlpha:SetScript("OnValueChanged",function(_,value)
        journal:SetSpellIDWindowOption("spellIDWindowAlpha",value)
        alphaLabel:SetText("Window background opacity: " .. math.floor(value*100+0.5) .. "%")
    end)
    options.spellIDBlacklist=button(optionsBody,"Spell ID window blacklist",255,-1006,265,function()
        if ns.SpellIDWindow then ns.SpellIDWindow:OpenBlacklist() end
    end)
    label(optionsBody,"Each row expires two minutes after observation unless kept indefinitely. The ID window is display-only. Automatic ability recording below works independently.",35,-1050,510,"GameFontHighlightSmall")
    options.singleObservationWindow=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.singleObservationWindow:SetPoint("TOPLEFT",30,-520); options.singleObservationWindow:SetSize(24,24)
    label(optionsBody,"Show only one Offenses, Defenses or Behaviour window",58,-526,470,"GameFontHighlightSmall")
    options.singleObservationWindow:SetScript("OnClick",function(self)
        journal:SetSingleObservationWindow(self:GetChecked() == true)
        callbacks.observationModeChanged()
    end)
    options.blockIncomingOffers=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.blockIncomingOffers:SetPoint("TOPLEFT",30,-626); options.blockIncomingOffers:SetSize(24,24)
    label(optionsBody,"Block incoming offers",58,-632,470,"GameFontHighlightSmall")
    options.blockIncomingOffers:SetScript("OnClick",function(self)
        journal:SetBlockIncomingOffers(self:GetChecked() == true)
    end)
    options.blockIncomingOffers:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT")
        GameTooltip:SetText("Block incoming offers")
        GameTooltip:AddLine("Automatically decline new offers and close unaccepted offers. Reports already accepted can still finish.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.blockIncomingOffers:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.alwaysAnchorToMain=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.alwaysAnchorToMain:SetPoint("TOPLEFT",30,-552); options.alwaysAnchorToMain:SetSize(24,24)
    label(optionsBody,"Always attempt to anchor to main window",58,-558,470,"GameFontHighlightSmall")
    options.alwaysAnchorToMain:SetScript("OnClick",function(self)
        journal:SetAlwaysAnchorToMain(self:GetChecked()==true)
        if self:GetChecked() and ns.WindowPositions then
            for _,window in ipairs({book.offensePicker,book.defensePicker,book.behaviourPicker}) do
                if window:IsShown() then ns.WindowPositions:AvoidWindowOverlap(window) end
            end
        end
    end)
    local scaleLabel=label(optionsBody,"UI scale: 100%",58,-392,460,"GameFontHighlightSmall")
    options.uiScale=CreateFrame("Slider",nil,optionsBody,"OptionsSliderTemplate")
    options.uiScale:SetPoint("TOPLEFT",30,-414); options.uiScale:SetSize(180,16)
    options.uiScale:SetMinMaxValues(0.5,1.5); options.uiScale:SetValueStep(0.05)
    options.uiScale:SetObeyStepOnDrag(true)
    local scaleTrack=options.uiScale:CreateTexture(nil,"BACKGROUND")
    scaleTrack:SetPoint("TOPLEFT",2,-4); scaleTrack:SetPoint("BOTTOMRIGHT",-2,4)
    scaleTrack:SetColorTexture(0.045,0.032,0.018,1)
    local pendingScale
    local function updateScaleControls(value)
        scaleLabel:SetText("UI scale: " .. math.floor(value*100+0.5) .. "%")
        options.uiScaleDecrease:SetEnabled(value>0.5)
        options.uiScaleIncrease:SetEnabled(value<1.5)
    end
    local function applyScale(value)
        value=math.max(0.5,math.min(1.5,value))
        options.uiScale:SetValue(value)
        pendingScale=nil
        journal:SetUIScale(value)
        updateScaleControls(value)
    end
    local function stepScale(percent)
        applyScale((math.floor(journal:GetUIScale()*100+0.5)+percent)/100)
    end
    options.uiScaleDecrease=button(optionsBody,"-",230,-409,28,function() stepScale(-5) end)
    options.uiScaleReset=button(optionsBody,"100%",264,-409,65,function() applyScale(1) end)
    options.uiScaleIncrease=button(optionsBody,"+",335,-409,28,function() stepScale(5) end)
    options.uiScale:SetScript("OnValueChanged",function(_,value)
        pendingScale=math.max(0.5,math.min(1.5,value))
        updateScaleControls(pendingScale)
    end)
    local function applyPendingScale()
        if pendingScale then applyScale(pendingScale) end
    end
    options.uiScale:SetScript("OnMouseUp",applyPendingScale)
    options.uiScale:EnableKeyboard(false)
    options.uiScale:SetScript("OnHide",function() pendingScale=nil end)
    options.showMinimapButton=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.showMinimapButton:SetPoint("TOPLEFT",30,-292); options.showMinimapButton:SetSize(24,24)
    label(optionsBody,"Show minimap button",58,-298,470,"GameFontHighlightSmall")
    options.showMinimapButton:SetScript("OnClick",function(self) journal:SetMinimapButton(self:GetChecked() == true) end)
    options.pointAnnouncements=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.pointAnnouncements:SetPoint("TOPLEFT",30,-180); options.pointAnnouncements:SetSize(24,24)
    label(optionsBody,"Show a chat message when knowledge is earned",58,-186,470,"GameFontHighlightSmall")
    options.pointAnnouncements:SetScript("OnClick",function(self) journal:SetPointAnnouncements(self:GetChecked() == true) end)
    options.creatureNotesFollowTarget=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.creatureNotesFollowTarget:SetPoint("TOPLEFT",30,-488); options.creatureNotesFollowTarget:SetSize(24,24)
    label(optionsBody,"Creature notes follow target selection",58,-494,470,"GameFontHighlightSmall")
    options.creatureNotesFollowTarget:SetScript("OnClick",function(self)
        journal:SetNotesFollowTarget(self:GetChecked() == true)
        callbacks.followNotesTarget()
    end)
    if type(StaticPopupDialogs) == "table" then
        StaticPopupDialogs.AZEROTHFIELDBOOK_BESTIARY_RESET_CONFIRM = {
            text = "Reset the " .. (journal:IsAccountWideTrackingActive() and "account-wide" or "character") .. " Azeroth Fieldbook Bestiary? This deletes its creature entries, notes, abilities, damage records and sharing knowledge/history, plus this character's settings. Saved backups and the Event log are kept.",
            button1 = YES, button2 = NO,
            OnAccept = function()
                journal:ResetDatabase()
                options.lockNewCritters:SetChecked(journal:GetLockNewCritters())
                options.autoRecordBuffs:SetChecked(journal:GetAutoRecordAbilities())
                options.autoLockEnabled:SetChecked(journal:GetAutoLockEnabled())
                options.autoLockKills:SetText(tostring(journal:GetAutoLockKills()))
                options.autoLockKills:SetEnabled(journal:GetAutoLockEnabled())
                options.blockIncomingOffers:SetChecked(journal:GetBlockIncomingOffers())
                options.alwaysAnchorToMain:SetChecked(journal:GetAlwaysAnchorToMain())
                refreshTrackingOption()
                shell:SetBackgroundBrightness(journal:GetBackgroundBrightness())
                callbacks.onReset()
            end,
            timeout = 0, whileDead = true, hideOnEscape = true, preferredIndex = 3,
        }
    end
    button(options,"Reset Bestiary",30,-722,160,function()
        if StaticPopup_Show then StaticPopup_Show("AZEROTHFIELDBOOK_BESTIARY_RESET_CONFIRM") end
    end)
    if ns.CreateBackupWindow and journal.CreateBackup then
        local backupWindow=ns.CreateBackupWindow(journal,{page=createBookPage,label=label,button=button},callbacks.onRestored)
        book.backupWindow=backupWindow
        options.backupButton=button(options,"Backup Bestiary",208,-722,160,function() backupWindow:Open(true) end)
        options.restoreButton=button(options,"Restore Bestiary",378,-722,160,function() backupWindow:Open(false) end)
    end
    options:SetScript("OnShow",function(self)
        showBookPage(self)
        refreshTrackingOption()
        options.singleObservationWindow:SetChecked(journal:GetSingleObservationWindow())
        options.lockNewCritters:SetChecked(journal:GetLockNewCritters())
        options.autoRecordBuffs:SetChecked(journal:GetAutoRecordAbilities())
        options.autoLockEnabled:SetChecked(journal:GetAutoLockEnabled())
        options.autoLockKills:SetText(tostring(journal:GetAutoLockKills()))
        options.autoLockKills:SetEnabled(journal:GetAutoLockEnabled())
        options.alwaysAnchorToMain:SetChecked(journal:GetAlwaysAnchorToMain())
        options.blockIncomingOffers:SetChecked(journal:GetBlockIncomingOffers())
        options.uiScale:SetValue(journal:GetUIScale())
        pendingScale=nil; updateScaleControls(journal:GetUIScale())
        options.showMinimapButton:SetChecked(journal:GetMinimapButton())
        options.pointAnnouncements:SetChecked(journal:GetPointAnnouncements())
        options.creatureNotesFollowTarget:SetChecked(journal:GetNotesFollowTarget())
        options.creatureAnnouncement:SetChecked(journal:GetCreatureAnnouncement())
        options.spellIDTooltips:SetChecked(journal:GetSpellIDTooltips())
        options.killCountTooltips:SetChecked(journal:GetKillCountTooltips())
        options.displayCastIDs:SetChecked(journal:GetDisplayCastIDs())
        for _, key in ipairs({"displaySpellIDWindow","spellIDWindowLocked","spellIDWindowIndefinite","displayHoveredAuraSnapshots","spellIDWindowAutoFade"}) do
            options[key]:SetChecked(journal:GetSpellIDWindowOption(key))
        end
        options.spellIDWindowAlpha:SetValue(journal:GetSpellIDWindowOption("spellIDWindowAlpha"))
        options.backgroundBrightness:SetValue(journal:GetBackgroundBrightness())
    end)
    options:Hide(); book.options=options
    shell:SetSectionPages("bestiary",{help=help,options=options,eventLog=eventLog})
end
