local _, ns = ...

-- Bestiary settings and help content; shared page frames live in FieldbookShell.
function ns.CreateBestiaryPages(journal,shell,book,callbacks)
    local ui=ns.FieldbookUI
    local label,button,edit=ui.Label,ui.Button,ui.Edit
    local function createBookPage(...) return shell:CreatePage(...) end
    local function showBookPage(page) shell:ShowPage(page) end
    local eventLog,eventBody=createBookPage("AzerothFieldbookEventLog","Event log",65)
    book.eventLog=eventLog
    local eventPage=0
    local eventText=label(eventBody,"",30,0,530,"GameFontHighlightSmall")
    local eventStatus=label(eventLog,"",255,-722,300,"GameFontHighlightSmall")
    local newer,older
    local function refreshEventLog()
        local log=journal:GetEventLog()
        local entries=log.entries
        eventPage=math.max(0,math.min(eventPage,math.max(0,math.ceil(#entries/50)-1)))
        local lines={}
        for index=#entries-eventPage*50,math.max(1,#entries-eventPage*50-49),-1 do
            local entry=entries[index]
            local stamp=entry.timestamp and date and date("%Y-%m-%d %H:%M:%S",entry.timestamp) or "Unknown time"
            lines[#lines+1]="|cff999999"..stamp.."|r\n"..entry.message
        end
        eventText:SetText(#lines>0 and table.concat(lines,"\n\n") or "No events recorded yet. Events are saved even when chat messages are disabled.")
        local contentHeight=math.max(1,eventText:GetStringHeight()+20)
        local height=math.max(200,math.min(767,eventLog.contentTop+contentHeight+65))
        local resized=eventLog:GetHeight()~=height
        eventLog:SetHeight(height)
        eventBody:SetHeight(contentHeight)
        local range=math.max(0,contentHeight-(height-eventLog.contentTop-65))
        eventLog.scroll:SetVerticalScroll(math.min(eventLog.scroll:GetVerticalScroll() or 0,range))
        eventLog.scroll:UpdateScrollChildRect()
        local bar=eventLog.scroll.ScrollBar
        if bar and type(bar)~="function" then bar:SetShown(range>0) end
        eventLog.scroll:EnableMouseWheel(range>0)
        if resized and eventLog:IsShown() and ns.WindowPositions then ns.WindowPositions:AvoidWindowOverlap(eventLog) end
        eventStatus:SetText(#entries.." events"..(#entries>50 and (" · Page "..(eventPage+1).." / "..math.ceil(#entries/50)) or ""))
        newer:SetShown(#entries>50);older:SetShown(#entries>50)
        newer:SetEnabled(eventPage>0);older:SetEnabled((eventPage+1)*50<#entries)
    end
    newer=button(eventLog,"Newer",30,-722,100,function() eventPage=eventPage-1;eventLog.scroll:SetVerticalScroll(0);refreshEventLog() end)
    older=button(eventLog,"Older",140,-722,100,function() eventPage=eventPage+1;eventLog.scroll:SetVerticalScroll(0);refreshEventLog() end)
    newer:ClearAllPoints();newer:SetPoint("BOTTOMLEFT",30,21)
    older:ClearAllPoints();older:SetPoint("BOTTOMLEFT",140,21)
    eventStatus:ClearAllPoints();eventStatus:SetPoint("BOTTOMRIGHT",-35,28)
    eventLog.text,eventLog.newer,eventLog.older=eventText,newer,older
    eventLog:SetScript("OnShow",refreshEventLog)
    journal:SetEventLogChangedCallback(function() if eventLog:IsShown() then refreshEventLog() end end)
    eventLog:Hide()
    local help,helpBody=createBookPage("AzerothFieldbookHelp","AZEROTH FIELDBOOK - HELP",24)
    local helpInstructions=label(helpBody,"|cffffd1001. Encounter|r\nBuild a creature journal by targeting or mousing over attackable NPCs. Readable names, creature types, zones and levels are recorded automatically. A skull means the level is unknown. While flying, including flight paths, target a creature or use the mouseover-open keybinding to record it; passive hovering does not count.\n\n|cffffd1002. Record|r\nCasts with readable spell IDs are automatically confirmed with a blue [A]; readable buffs are recorded outside combat. Change this under Options > Ability recording. Observed fleeing can also record Flees at low health. Other ability observations may remain pending for your review. Add missing abilities and damage observations manually; use your own measurements for damage ranges.\n\n|cffffd1003. Review|r\nSelect a creature to review abilities, defenses, behaviour and Notes. Confirm accurate abilities, reject doubtful ones or remove unwanted records. Optional Show expected immunities in Options starts off: [Type] labels are expectations, not observed or shareable immunity marks.\n\nOpen Locations and switch between Tracking: Kills and Tracking: Observations. Violet marks credited kills; cyan marks your position when targeting the creature. Approximate markers are not exact creature positions. Hover zone names in the entry to see observed subzones.\n\n|cffffd1004. Lock Entry|r\nUse Lock this entry to protect manual edits and the saved basic information; Unlock this entry resumes editing. Locking does not stop kill credit or fresh automatic abilities and behaviours. Some basic facts, such as disposition and previously unknown levels, can still update. Notes remain editable.\n\nConfirmed abilities can appear in creature tooltips. Use each ability's checkbox to choose which ones appear, even while locked. Hold Ctrl over a creature for available spell descriptions.\n\n|cffffd1005. Browse|r\nNarrow the index with creature-type filters, search and sorting. Index shows or hides the A-Z filters. The Next Bestiary entry and Previous Bestiary entry keybindings follow the filtered list while the Bestiary is open and no text field has focus.\n\nAccount-wide tracking in Options starts on and covers all seven journals. Turn it off to use this character's separate journals; changes apply after /reload. Existing character journals import once into the account journals. Later changes in the two scopes stay separate.\n\n|cffffd1006. Share|r\nOutside combat, use Share to offer one creature's information to a named player using the same addon version. Select the traits to include and review the cost before Send. Received traits appear as unverified Rumours with the sender's name. Open Rumours, then use the green tick to verify a claim or x to reject it. Unlock the entry before verifying. Beast Lore is shared separately as a free, read-only client observation with sender attribution.\n\nThe book shows knowledge earned; Share shows what remains available after spending and reservations. If delivery is uncertain, knowledge stays spent. Reopen Share and use Retry for the same report without another charge, up to three times within 24 hours.",35,0,535)
    local pointsBlock=CreateFrame("Frame",nil,helpBody,"BackdropTemplate")
    pointsBlock:SetPoint("TOPLEFT",helpInstructions,"BOTTOMLEFT",0,-18)
    pointsBlock:SetWidth(535)
    pointsBlock:SetBackdrop({bgFile="Interface\\Buttons\\WHITE8X8",edgeFile="Interface\\Tooltips\\UI-Tooltip-Border",edgeSize=12,insets={left=3,right=3,top=3,bottom=3}})
    pointsBlock:SetBackdropColor(0.12,0.08,0.03,0.35)
    pointsBlock:SetBackdropBorderColor(0.55,0.40,0.20,1)
    pointsBlock.title=label(pointsBlock,"Knowledge",14,-14,507,"GameFontNormalLarge")
    pointsBlock.title:SetTextColor(1,0.82,0.14)
    pointsBlock.awardHeading=label(pointsBlock,"Earning knowledge",14,0,507,"GameFontNormal")
    pointsBlock.awardHeading:SetTextColor(1,0.82,0.14)
    pointsBlock.awards=label(pointsBlock,"+1 for first kill\n+1 for silver star (10 kills)\n+2 for gold star (25 kills)\n+3 for crown (50 kills)\n\nElite: 1.5x each award. Rare and Rare Elite: 2x, without stacking. Round each award down to a whole point.\n\nQualifying kills earn knowledge even at an unknown/skull level. Discovery, locations, levels and received reports earn none. Each milestone pays once per creature; deleting an entry does not reset its credit.",14,0,507,"GameFontHighlightSmall")
    pointsBlock.spendHeading=label(pointsBlock,"Sharing knowledge",14,0,507,"GameFontNormal")
    pointsBlock.spendHeading:SetTextColor(1,0.82,0.14)
    pointsBlock.spending=label(pointsBlock,"1 knowledge for basic information; free if the recipient already knows it.\n1 knowledge per selected rumour.\n\nRemove known basics from the cost, then multiply the total by 1.5 for Elite or 2 for Rare and Rare Elite and round down. Beast Lore reports are free.\n\nSend reserves the maximum cost; acceptance spends the final cost. Declines and cancellation before spending are free. Receiving information is free.",14,0,507,"GameFontHighlightSmall")
    help.pointsBlock=pointsBlock
    local helpDetails=CreateFrame("Frame",nil,helpBody)
    helpDetails:SetPoint("TOPLEFT",pointsBlock,"BOTTOMLEFT",-35,-18)
    helpDetails:SetWidth(570)
    label(helpDetails,"|cffffd100ABOUT|r",35,0,120,"GameFontNormal")
    local about=label(helpDetails,"Created by |cff40c7ebSpinkler|r\nSPECIAL THANKS to |cfff48cbaErna|r, |cffaad372Labrick|r, and |cffff7c0aRhysdogg|r for beta testing\n\nDeveloped with AI-assisted coding tools.\nDesign, direction, testing and final development decisions by the author.",35,-22,535,"GameFontHighlightSmall")
    help:SetScript("OnShow",function(self)
        local pointsHeight=14
        for i,text in ipairs({pointsBlock.title,pointsBlock.awardHeading,pointsBlock.awards,pointsBlock.spendHeading,pointsBlock.spending}) do
            if i>1 then pointsHeight=pointsHeight+((i==2 or i==4) and 16 or 8) end
            text:ClearAllPoints(); text:SetPoint("TOPLEFT",14,-pointsHeight)
            pointsHeight=pointsHeight+text:GetStringHeight()
        end
        pointsHeight=pointsHeight+14
        pointsBlock:SetHeight(pointsHeight)
        helpDetails:SetHeight(22+about:GetStringHeight())
        helpBody:SetHeight(helpInstructions:GetStringHeight()+18+pointsHeight+18+22+about:GetStringHeight()+16)
        showBookPage(self)
    end)
    help:Hide(); book.help=help
    local options,optionsBody=createBookPage("AzerothFieldbookOptions","AZEROTH FIELDBOOK - OPTIONS",65)
    optionsBody:SetHeight(2105)
    local function optionHeading(title,y)
        local heading=label(optionsBody,title,30,-y,510,"GameFontNormalLarge")
        heading:SetTextColor(1,0.82,0.14)
        local font,size,flags=heading:GetFont()
        if font and type(size)=="number" then heading:SetFont(font,size-2,flags) end
    end
    optionHeading("Tracking",0)
    optionHeading("Chat notifications",122)
    label(optionsBody,"Events are saved in the Event log even when chat messages are off.",35,-216,510,"GameFontHighlightSmall")
    optionHeading("Appearance",266)
    optionHeading("Window behavior",562)
    optionHeading("Sharing",700)
    optionHeading("Tooltips and cast IDs",774)
    optionHeading("Ability recording",1204)
    options.autoRecordBuffs=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.autoRecordBuffs:SetPoint("TOPLEFT",30,-1230);options.autoRecordBuffs:SetSize(24,24)
    label(optionsBody,"Automatically record verified creature abilities",58,-1236,470,"GameFontHighlightSmall")
    label(optionsBody,"Readable cast IDs work in combat; buffs require both you and the creature out of combat. New records get a blue [A] and chat/Event log messages. Fresh evidence restores removed or rejected abilities even on locked entries; turn off to keep them removed.",35,-1268,510,"GameFontHighlightSmall")
    options.autoRecordBuffs:SetScript("OnClick",function(self)
        journal:SetAutoRecordAbilities(self:GetChecked()==true)
    end)
    optionHeading("Expected immunities",1360)
    options.expectedImmunities=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.expectedImmunities:SetPoint("TOPLEFT",30,-1386);options.expectedImmunities:SetSize(24,24)
    label(optionsBody,"Show expected immunities",58,-1392,470,"GameFontHighlightSmall")
    label(optionsBody,"Off by default. Optional creature-type guidance, not knowledge your character has observed. Hides or shows [Type] suggestions without changing recorded immunities or saved overrides.",35,-1424,510,"GameFontHighlightSmall")
    options.expectedImmunities:SetScript("OnClick",function(self)
        journal:SetShowExpectedImmunities(self:GetChecked()==true)
    end)
    optionHeading("Lorekeeper's Chronicle",1640)
    options.autoArchiveLore=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.autoArchiveLore:SetPoint("TOPLEFT",30,-1666);options.autoArchiveLore:SetSize(24,24)
    label(optionsBody,"Automatically archive readable lore",58,-1672,470,"GameFontHighlightSmall")
    options.autoArchiveLore:SetScript("OnClick",function(self)
        if ns.LoreSettings then ns.LoreSettings.Set("autoArchiveLore",self:GetChecked()==true) end
    end)
    options.loreOnlyOpenedPages=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.loreOnlyOpenedPages:SetPoint("TOPLEFT",30,-1700);options.loreOnlyOpenedPages:SetSize(24,24)
    label(optionsBody,"Only archive pages I open",58,-1706,470,"GameFontHighlightSmall")
    options.loreOnlyOpenedPages:SetScript("OnClick",function(self)
        if ns.LoreSettings then ns.LoreSettings.Set("loreOnlyOpenedPages",self:GetChecked()==true) end
    end)
    label(optionsBody,"Both start on. Only displayed pages are archived by default. Disable the second option to archive the whole accessible book where supported; the original reader may turn pages. Keep the interaction open until archiving finishes. Automatically retrieved pages are labelled separately. Disabling capture or enabling the restriction stops automatic work and keeps stored text. Manual capture and transcription remain available.",35,-1740,510,"GameFontHighlightSmall")
    options.accountWideTracking=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.accountWideTracking:SetPoint("TOPLEFT",30,-26); options.accountWideTracking:SetSize(24,24)
    label(optionsBody,"Account-wide tracking",58,-32,235,"GameFontHighlightSmall")
    options.scope=CreateFrame("Frame",nil,optionsBody)
    options.scope:SetPoint("TOPLEFT",300,-29);options.scope:SetSize(235,18)
    options.scope:EnableMouse(true)
    options.scopeLabel=label(options.scope,"",0,-3,235,"GameFontHighlightSmall")
    options.scopeLabel:SetTextColor(0.55,0.57,0.57);options.scopeLabel:SetWordWrap(false)
    function options:RefreshStorageScope()
        local title,explanation=shell:GetStorageScope()
        self.scopeLabel:SetText(title or (journal:IsAccountWideTrackingActive() and "Account-wide" or "Character-specific"))
        self.scopeExplanation=explanation
    end
    options.scope:SetScript("OnEnter",function(self)
        if GameTooltip then
            GameTooltip:SetOwner(self,"ANCHOR_RIGHT");GameTooltip:SetText(options.scopeLabel:GetText())
            if options.scopeExplanation then GameTooltip:AddLine(options.scopeExplanation,1,1,1,true) end
            GameTooltip:Show()
        end
    end)
    options.scope:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.trackingReload=label(optionsBody,"",58,-48,470,"GameFontHighlightSmall")
    options.trackingReload:SetWordWrap(false)
    local function refreshTrackingOption()
        options.accountWideTracking:SetChecked(journal:GetAccountWideTracking())
        options.trackingReload:SetText(journal:IsTrackingChangePending() and "Applies after /reload" or "")
        options:RefreshStorageScope()
    end
    options.accountWideTracking:SetScript("OnClick",function(self)
        journal:SetAccountWideTracking(self:GetChecked() == true)
        refreshTrackingOption()
    end)
    options.accountWideTracking:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT")
        GameTooltip:SetText("Account-wide tracking")
        GameTooltip:AddLine("Share knowledge across every Fieldbook section: Bestiary, Herbs & Minerals, Atlas, Almanac, Ledger, Treasure and Lore. Turn off to use this character's separate journals. Changes apply after /reload.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.accountWideTracking:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.autoLockEnabled=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.autoLockEnabled:SetPoint("TOPLEFT",30,-58);options.autoLockEnabled:SetSize(24,24)
    label(optionsBody,"Auto-lock after",58,-64,100,"GameFontHighlightSmall")
    options.autoLockKills=edit(optionsBody,166,-60,45,5)
    options.autoLockKills:SetNumeric(true)
    label(optionsBody,"kills without changes",226,-64,300,"GameFontHighlightSmall")
    options.autoLockEnabled:SetScript("OnClick",function(self)
        journal:SetAutoLockEnabled(self:GetChecked()==true)
        options.autoLockKills:SetEnabled(journal:GetAutoLockEnabled())
    end)
    options.autoLockKills:SetScript("OnEditFocusLost",function(self)
        journal:SetAutoLockKills(self:GetText())
        self:SetText(tostring(journal:GetAutoLockKills()))
    end)
    options.lockNewCritters=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.lockNewCritters:SetPoint("TOPLEFT",30,-90);options.lockNewCritters:SetSize(24,24)
    label(optionsBody,"Lock newly encountered critters",58,-96,470,"GameFontHighlightSmall")
    options.lockNewCritters:SetScript("OnClick",function(self)
        journal:SetLockNewCritters(self:GetChecked()==true)
    end)
    options.lockNewCritters:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT")
        GameTooltip:SetText("Lock newly encountered critters")
        GameTooltip:AddLine("Start new critter entries locked after recording their basic information. Existing entries and manual unlocks are kept. Automatic [A] records still apply; unlock for manual edits.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.lockNewCritters:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.creatureAnnouncement=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.creatureAnnouncement:SetPoint("TOPLEFT",30,-148); options.creatureAnnouncement:SetSize(24,24)
    label(optionsBody,"Show chat messages for new creatures, nodes and locations",58,-154,460,"GameFontHighlightSmall")
    options.creatureAnnouncement:SetScript("OnClick",function(self) journal:SetCreatureAnnouncement(self:GetChecked() == true) end)
    options.spellIDTooltips=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.spellIDTooltips:SetPoint("TOPLEFT",30,-826); options.spellIDTooltips:SetSize(24,24)
    label(optionsBody,"Show spell IDs on tooltips if possible",58,-832,460,"GameFontHighlightSmall")
    options.spellIDTooltips:SetScript("OnClick",function(self) journal:SetSpellIDTooltips(self:GetChecked() == true) end)
    options.spellIDTooltips:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT")
        GameTooltip:SetText("Spell IDs on tooltips")
        GameTooltip:AddLine("Starts on. Applies WoW's client-wide spell/aura ID tooltip preference at login and when changed here, and controls Fieldbook tooltip IDs. Your choice is saved; a Bestiary settings reset restores the default.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.spellIDTooltips:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.displayCastIDs=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.displayCastIDs:SetPoint("TOPLEFT",30,-852); options.displayCastIDs:SetSize(24,24)
    label(optionsBody,"Display Cast IDs",58,-858,460,"GameFontHighlightSmall")
    options.displayCastIDs:SetScript("OnClick",function(self) journal:SetDisplayCastIDs(self:GetChecked() == true) end)
    label(optionsBody,"Background brightness",58,-332,170,"GameFontHighlightSmall")
    options.backgroundBrightness=CreateFrame("Slider",nil,optionsBody,"OptionsSliderTemplate")
    options.backgroundBrightness:SetPoint("TOPLEFT",30,-354)
    options.backgroundBrightness:SetSize(180,16)
    local brightnessTrack=options.backgroundBrightness:CreateTexture(nil,"BACKGROUND")
    brightnessTrack:SetPoint("TOPLEFT",2,-4)
    brightnessTrack:SetPoint("BOTTOMRIGHT",-2,4)
    brightnessTrack:SetColorTexture(0.045,0.032,0.018,1)
    options.backgroundBrightness:SetMinMaxValues(0.5,1.5)
    options.backgroundBrightness:SetValueStep(0.05)
    options.backgroundBrightness:SetObeyStepOnDrag(true)
    options.backgroundBrightness:SetScript("OnValueChanged",function(_,value)
        journal:SetBackgroundBrightness(value)
        shell:SetBackgroundBrightness(value)
    end)
    options.darkMode=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.darkMode:SetPoint("TOPLEFT",255,-348);options.darkMode:SetSize(24,24)
    label(optionsBody,"Dark Mode",283,-354,230,"GameFontHighlightSmall")
    options.darkMode:SetScript("OnClick",function(self)
        journal:SetDarkMode(self:GetChecked()==true)
        shell:SetDarkMode(journal:GetDarkMode())
    end)
    options.killCountTooltips=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.killCountTooltips:SetPoint("TOPLEFT",30,-800);options.killCountTooltips:SetSize(24,24)
    label(optionsBody,"Show kill count in creature tooltips",58,-806,460,"GameFontHighlightSmall")
    options.killCountTooltips:SetScript("OnClick",function(self) journal:SetKillCountTooltips(self:GetChecked()==true) end)
    options.behaviourTooltips=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.behaviourTooltips:SetPoint("TOPLEFT",30,-878);options.behaviourTooltips:SetSize(24,24)
    label(optionsBody,"Show behaviour traits in creature tooltips",58,-884,460,"GameFontHighlightSmall")
    options.behaviourTooltips:SetScript("OnClick",function(self) journal:SetBehaviourTooltips(self:GetChecked()==true) end)
    options.behaviourTooltips:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT");GameTooltip:SetText("Behaviour traits in creature tooltips")
        GameTooltip:AddLine("Show checked Behaviour traits such as Melee, Patrols and Flees at low health. Disposition and unverified Rumours are excluded. Off by default.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.behaviourTooltips:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    optionHeading("Spell ID window",914)
    local function windowCheck(key, title, y)
        local check=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
        check:SetPoint("TOPLEFT",30,y); check:SetSize(24,24)
        label(optionsBody,title,58,y-6,470,"GameFontHighlightSmall")
        check:SetScript("OnClick",function(self) journal:SetSpellIDWindowOption(key,self:GetChecked() == true) end)
        options[key]=check
    end
    windowCheck("displaySpellIDWindow","Display Spell ID window",-940)
    windowCheck("spellIDWindowLocked","Lock Spell ID window",-968)
    windowCheck("spellIDWindowIndefinite","Display Spell IDs in the ID window indefinitely",-996)
    windowCheck("displayHoveredAuraSnapshots","Retain hovered aura tooltips",-1024)
    windowCheck("spellIDWindowAutoFade","Auto-fade when the Spell ID window contains no data",-1052)
    local alphaLabel=label(optionsBody,"Window background opacity: 35%",58,-1090,460,"GameFontHighlightSmall")
    options.spellIDWindowAlpha=CreateFrame("Slider",nil,optionsBody,"OptionsSliderTemplate")
    options.spellIDWindowAlpha:SetPoint("TOPLEFT",30,-1110); options.spellIDWindowAlpha:SetSize(180,16)
    local alphaTrack=options.spellIDWindowAlpha:CreateTexture(nil,"BACKGROUND")
    alphaTrack:SetPoint("TOPLEFT",2,-4)
    alphaTrack:SetPoint("BOTTOMRIGHT",-2,4)
    alphaTrack:SetColorTexture(0.045,0.032,0.018,1)
    options.spellIDWindowAlpha:SetMinMaxValues(0,1); options.spellIDWindowAlpha:SetValueStep(0.05)
    options.spellIDWindowAlpha:SetObeyStepOnDrag(true)
    options.spellIDWindowAlpha:SetScript("OnValueChanged",function(_,value)
        journal:SetSpellIDWindowOption("spellIDWindowAlpha",value)
        alphaLabel:SetText("Window background opacity: " .. math.floor(value*100+0.5) .. "%")
    end)
    options.spellIDBlacklist=button(optionsBody,"Spell ID window blacklist",255,-1106,265,function()
        if ns.SpellIDWindow then ns.SpellIDWindow:OpenBlacklist() end
    end)
    label(optionsBody,"Each row expires two minutes after observation unless kept indefinitely. The ID window is display-only. Automatic ability recording below works independently.",35,-1150,510,"GameFontHighlightSmall")
    label(optionsBody,"Offenses, Defenses and Behaviour replace the abilities area.",35,-626,510,"GameFontHighlightSmall")
    options.blockIncomingOffers=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.blockIncomingOffers:SetPoint("TOPLEFT",30,-726); options.blockIncomingOffers:SetSize(24,24)
    label(optionsBody,"Block incoming offers",58,-732,470,"GameFontHighlightSmall")
    options.blockIncomingOffers:SetScript("OnClick",function(self)
        journal:SetBlockIncomingOffers(self:GetChecked() == true)
    end)
    options.blockIncomingOffers:SetScript("OnEnter",function(self)
        if not GameTooltip then return end
        GameTooltip:SetOwner(self,"ANCHOR_RIGHT")
        GameTooltip:SetText("Block incoming offers")
        GameTooltip:AddLine("Automatically decline new offers and close unaccepted offers. Reports already accepted can still finish.",1,1,1,true)
        GameTooltip:Show()
    end)
    options.blockIncomingOffers:SetScript("OnLeave",function() if GameTooltip then GameTooltip:Hide() end end)
    options.alwaysAnchorToMain=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.alwaysAnchorToMain:SetPoint("TOPLEFT",30,-652); options.alwaysAnchorToMain:SetSize(24,24)
    label(optionsBody,"Always attempt to anchor to main window",58,-658,470,"GameFontHighlightSmall")
    options.alwaysAnchorToMain:SetScript("OnClick",function(self)
        journal:SetAlwaysAnchorToMain(self:GetChecked()==true)
    end)
    local scaleLabel=label(optionsBody,"UI scale: 100%",58,-392,460,"GameFontHighlightSmall")
    options.uiScale=CreateFrame("Slider",nil,optionsBody,"OptionsSliderTemplate")
    options.uiScale:SetPoint("TOPLEFT",30,-414); options.uiScale:SetSize(180,16)
    options.uiScale:SetMinMaxValues(0.5,1.5); options.uiScale:SetValueStep(0.05)
    options.uiScale:SetObeyStepOnDrag(true)
    local scaleTrack=options.uiScale:CreateTexture(nil,"BACKGROUND")
    scaleTrack:SetPoint("TOPLEFT",2,-4); scaleTrack:SetPoint("BOTTOMRIGHT",-2,4)
    scaleTrack:SetColorTexture(0.045,0.032,0.018,1)
    local pendingScale
    local function updateScaleControls(value)
        scaleLabel:SetText("UI scale: " .. math.floor(value*100+0.5) .. "%")
        options.uiScaleDecrease:SetEnabled(value>0.5)
        options.uiScaleIncrease:SetEnabled(value<1.5)
    end
    local function applyScale(value)
        value=math.max(0.5,math.min(1.5,value))
        options.uiScale:SetValue(value)
        pendingScale=nil
        journal:SetUIScale(value)
        updateScaleControls(value)
    end
    local function stepScale(percent)
        applyScale((math.floor(journal:GetUIScale()*100+0.5)+percent)/100)
    end
    options.uiScaleDecrease=button(optionsBody,"-",230,-409,28,function() stepScale(-5) end)
    options.uiScaleReset=button(optionsBody,"100%",264,-409,65,function() applyScale(1) end)
    options.uiScaleIncrease=button(optionsBody,"+",335,-409,28,function() stepScale(5) end)
    options.uiScale:SetScript("OnValueChanged",function(_,value)
        pendingScale=math.max(0.5,math.min(1.5,value))
        updateScaleControls(pendingScale)
    end)
    local function applyPendingScale()
        if pendingScale then applyScale(pendingScale) end
    end
    options.uiScale:SetScript("OnMouseUp",applyPendingScale)
    options.uiScale:EnableKeyboard(false)
    options.uiScale:SetScript("OnHide",function() pendingScale=nil end)
    local textSizeLabel=label(optionsBody,"Text size: Default",58,-450,460,"GameFontHighlightSmall")
    options.textSize=CreateFrame("Slider",nil,optionsBody,"OptionsSliderTemplate")
    options.textSize:SetPoint("TOPLEFT",30,-476);options.textSize:SetSize(180,16)
    options.textSize:SetMinMaxValues(-3,3);options.textSize:SetValueStep(1)
    options.textSize:SetObeyStepOnDrag(true);options.textSize:EnableKeyboard(false)
    local textTrack=options.textSize:CreateTexture(nil,"BACKGROUND")
    textTrack:SetPoint("TOPLEFT",2,-4);textTrack:SetPoint("BOTTOMRIGHT",-2,4)
    textTrack:SetColorTexture(0.045,0.032,0.018,1)
    local function updateTextSizeControls()
        local value=ns.TextSize and ns.TextSize:Get() or 0
        textSizeLabel:SetText("Text size: "..(value==0 and "Default" or string.format("%+d points",value)))
        options.textSizeReload:SetEnabled(ns.TextSize and ns.TextSize:NeedsReload() or false)
    end
    options.textSizeReset=button(optionsBody,"Default",230,-471,85,function()
        if ns.TextSize then ns.TextSize:Set(0) end
        options.textSize:SetValue(0);updateTextSizeControls()
    end)
    options.textSizeReload=button(optionsBody,"Apply / reload",325,-471,150,function()
        if ReloadUI then ReloadUI() end
    end)
    label(optionsBody,"Seven steps (-3 to +3 points). Applies after reloading the UI.",35,-510,510,"GameFontHighlightSmall")
    options.textSize:SetScript("OnValueChanged",function(_,value)
        if ns.TextSize then ns.TextSize:Set(value) end
        updateTextSizeControls()
    end)
    options.showMinimapButton=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.showMinimapButton:SetPoint("TOPLEFT",30,-292); options.showMinimapButton:SetSize(24,24)
    label(optionsBody,"Show minimap button",58,-298,470,"GameFontHighlightSmall")
    options.showMinimapButton:SetScript("OnClick",function(self) journal:SetMinimapButton(self:GetChecked() == true) end)
    options.pointAnnouncements=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.pointAnnouncements:SetPoint("TOPLEFT",30,-180); options.pointAnnouncements:SetSize(24,24)
    label(optionsBody,"Show a chat message when knowledge is earned",58,-186,470,"GameFontHighlightSmall")
    options.pointAnnouncements:SetScript("OnClick",function(self) journal:SetPointAnnouncements(self:GetChecked() == true) end)
    options.creatureNotesFollowTarget=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.creatureNotesFollowTarget:SetPoint("TOPLEFT",30,-588); options.creatureNotesFollowTarget:SetSize(24,24)
    label(optionsBody,"Creature notes follow target selection",58,-594,470,"GameFontHighlightSmall")
    options.creatureNotesFollowTarget:SetScript("OnClick",function(self)
        journal:SetNotesFollowTarget(self:GetChecked() == true)
        callbacks.followNotesTarget()
    end)
    optionHeading("Atlas and Almanac maps",1500)
    options.mapClickNavigation=CreateFrame("CheckButton",nil,optionsBody,"UICheckButtonTemplate")
    options.mapClickNavigation:SetPoint("TOPLEFT",30,-1526);options.mapClickNavigation:SetSize(24,24)
    label(optionsBody,"World-map click navigation",58,-1532,470,"GameFontHighlightSmall")
    label(optionsBody,"Left-click a zone to enter it; right-click to view its parent map. Scroll-wheel zoom and marker actions remain available.",35,-1562,510,"GameFontHighlightSmall")
    options.mapClickNavigation:SetScript("OnClick",function(self) journal:SetMapClickNavigation(self:GetChecked()==true) end)
    if type(StaticPopupDialogs) == "table" then
        StaticPopupDialogs.AZEROTHFIELDBOOK_BESTIARY_RESET_CONFIRM = {
            text = "Reset the " .. (journal:IsAccountWideTrackingActive() and "account-wide" or "character") .. " Azeroth Fieldbook Bestiary? This deletes its creature entries, notes, abilities, damage records and sharing knowledge/history, plus this character's settings. Saved backups and the Event log are kept.",
            button1 = YES, button2 = NO,
            OnAccept = function()
                journal:ResetDatabase()
                options.behaviourTooltips:SetChecked(journal:GetBehaviourTooltips())
                options.lockNewCritters:SetChecked(journal:GetLockNewCritters())
                options.autoRecordBuffs:SetChecked(journal:GetAutoRecordAbilities())
                options.autoLockEnabled:SetChecked(journal:GetAutoLockEnabled())
                options.autoLockKills:SetText(tostring(journal:GetAutoLockKills()))
                options.autoLockKills:SetEnabled(journal:GetAutoLockEnabled())
                options.blockIncomingOffers:SetChecked(journal:GetBlockIncomingOffers())
                options.alwaysAnchorToMain:SetChecked(journal:GetAlwaysAnchorToMain())
                options.mapClickNavigation:SetChecked(journal:GetMapClickNavigation())
                refreshTrackingOption()
                options.darkMode:SetChecked(journal:GetDarkMode())
                shell:SetDarkMode(journal:GetDarkMode())
                shell:SetBackgroundBrightness(journal:GetBackgroundBrightness())
                callbacks.onReset()
            end,
            timeout = 0, whileDead = true, hideOnEscape = true, preferredIndex = 3,
        }
    end
    button(options,"Reset Bestiary",30,-722,160,function()
        if StaticPopup_Show then StaticPopup_Show("AZEROTHFIELDBOOK_BESTIARY_RESET_CONFIRM") end
    end)
    if ns.CreateBackupWindow and journal.CreateBackup then
        local backupWindow=ns.CreateBackupWindow(journal,{page=createBookPage,label=label,button=button},callbacks.onRestored)
        book.backupWindow=backupWindow
        options.backupButton=button(options,"Backup Bestiary",208,-722,160,function() backupWindow:Open(true) end)
        options.restoreButton=button(options,"Restore Bestiary",378,-722,160,function() backupWindow:Open(false) end)
    end
    if ns.OpenFieldbookBackups then
        optionHeading("Whole-Fieldbook backup and recovery",1900)
        label(optionsBody,"Protect all seven journals, including private notes, the account journals and this character's retained journals. Export a copy outside the game. Reports are not backups.",35,-1934,510,"GameFontHighlightSmall")
        options.fieldbookBackups=button(optionsBody,"Fieldbook backups",30,-2012,200,function() ns.OpenFieldbookBackups() end)
        label(optionsBody,"Also available with /fieldbook backups, even if normal startup is blocked.",35,-2050,510,"GameFontHighlightSmall")
    end
    options:SetScript("OnShow",function(self)
        showBookPage(self)
        refreshTrackingOption()
        options.mapClickNavigation:SetChecked(journal:GetMapClickNavigation())
        options.lockNewCritters:SetChecked(journal:GetLockNewCritters())
        options.autoRecordBuffs:SetChecked(journal:GetAutoRecordAbilities())
        options.autoLockEnabled:SetChecked(journal:GetAutoLockEnabled())
        options.autoLockKills:SetText(tostring(journal:GetAutoLockKills()))
        options.autoLockKills:SetEnabled(journal:GetAutoLockEnabled())
        options.alwaysAnchorToMain:SetChecked(journal:GetAlwaysAnchorToMain())
        options.blockIncomingOffers:SetChecked(journal:GetBlockIncomingOffers())
        options.uiScale:SetValue(journal:GetUIScale())
        pendingScale=nil; updateScaleControls(journal:GetUIScale())
        options.textSize:SetValue(ns.TextSize and ns.TextSize:Get() or 0)
        updateTextSizeControls()
        options.showMinimapButton:SetChecked(journal:GetMinimapButton())
        options.pointAnnouncements:SetChecked(journal:GetPointAnnouncements())
        options.creatureNotesFollowTarget:SetChecked(journal:GetNotesFollowTarget())
        options.creatureAnnouncement:SetChecked(journal:GetCreatureAnnouncement())
        options.spellIDTooltips:SetChecked(journal:GetSpellIDTooltips())
        options.killCountTooltips:SetChecked(journal:GetKillCountTooltips())
        options.behaviourTooltips:SetChecked(journal:GetBehaviourTooltips())
        options.expectedImmunities:SetChecked(journal:GetShowExpectedImmunities())
        options.autoArchiveLore:SetChecked(not ns.LoreSettings or ns.LoreSettings.Get("autoArchiveLore"))
        options.loreOnlyOpenedPages:SetChecked(not ns.LoreSettings or ns.LoreSettings.Get("loreOnlyOpenedPages"))
        options.displayCastIDs:SetChecked(journal:GetDisplayCastIDs())
        for _, key in ipairs({"displaySpellIDWindow","spellIDWindowLocked","spellIDWindowIndefinite","displayHoveredAuraSnapshots","spellIDWindowAutoFade"}) do
            options[key]:SetChecked(journal:GetSpellIDWindowOption(key))
        end
        options.spellIDWindowAlpha:SetValue(journal:GetSpellIDWindowOption("spellIDWindowAlpha"))
        options.darkMode:SetChecked(journal:GetDarkMode())
        options.backgroundBrightness:SetValue(journal:GetBackgroundBrightness())
    end)
    options:Hide(); book.options=options
    shell:SetSectionPages("bestiary",{help=help,options=options,eventLog=eventLog})
end
