"""Measure the shipping Lua sampler/codec, not a Python reimplementation.

Run: python -B -X utf8 tests/annals_storage.py --write
Fixtures represent six hours, in two-second observations; no player data is read.
"""
from pathlib import Path
import sys
from annals_test_harness import client

SIMULATION=r'''
function diskSize(v,depth)
    depth=depth or 0
    if type(v)=='string' then return #string.format('%q',v) end
    if type(v)~='table' then return #tostring(v) end
    local n=3
    for k,x in pairs(v) do n=n+(depth+1)+1+diskSize(k,depth+1)+4+diskSize(x,depth+1)+2 end
    return n+depth
end
function measure(mode,options,hours)
    reset();trail=ns.CreateAnnalsTrail(j,options or {})
    local travelled=0;local lastX,lastY=2500,2500;local duration=hours*3600
    for at=0,duration,2 do
        local moving=mode~='stationary' and (mode~='mixed' or at%1800<600)
        local x,y=lastX,lastY
        if moving then
            travelled=travelled+2
            -- Meandering roads with repeated bends and local detours. Normalized
            -- map motion, not a promise about yard speeds in every zone.
            x=5000+3200*math.sin(travelled/280)+300*math.sin(travelled/31)
            y=5000+2500*math.cos(travelled/350)+220*math.sin(travelled/19)
            if mode=='pessimistic' then
                x=5000+2500*math.sin(travelled/90)+130*math.sin(travelled*0.9)
                y=5000+2400*math.cos(travelled/105)+120*math.cos(travelled*0.9)
            end
            x,y=math.floor(x+0.5),math.floor(y+0.5)
        end
        -- Hourly loading transition, half-hour zone changes during movement.
        if at>0 and at%3600==0 and mode~='stationary' then trail:Break('loading') end
        local map=mode=='stationary' and 101 or 101+math.floor(travelled/1800)%3
        trail:Sample({x=x,y=y,at=1800000000+at,mapID=map,level=23,context='false:false'})
        lastX,lastY=x,y
    end
    trail:Break('logout')
    local count,payload=0,0
    for _,s in ipairs(db.segments) do local p=assert(ns.Annals.Decode(s));count=count+#p;payload=payload+#s.data end
    return {points=count,payload=payload,segments=#db.segments,saved=diskSize(db.segments),hours=hours}
end
'''


def measurements(hours=6):
    lua=client();lua.execute(SIMULATION)
    results=[]
    for mode,label,options in [
        ('stationary','Stationary',{}),
        ('continuous','Continuous meandering travel',{}),
        ('mixed','Mixed play: 1/3 travelling, 2/3 idle',{}),
        ('pessimistic','Pessimistic: continuous tight turns',{}),
        ('continuous','Continuous, simplification disabled',{'simplify':False}),
        ('continuous','Previous prototype: continuous',{'interval':0,'minimum':20,'distance':80,'seconds':30,'turn':12,'tolerance':10}),
        ('pessimistic','Previous prototype: tight turns',{'interval':0,'minimum':20,'distance':80,'seconds':30,'turn':12,'tolerance':10}),
    ]:
        result=dict(lua.globals().measure(mode,lua.table_from(options),hours).items())
        result['label']=label;results.append(result)
    lua.execute('''
        reset();j:Quest('accepted',42,'The Lost Expedition',nil,{mapID=101,x=3820,y=4760,zone='Northern Stranglethorn',subzone='Nesingwary Expedition',level=24},1800000000)
        acceptedBytes=diskSize(db.events[1])
        j:Quest('completed',42,'The Lost Expedition',{chosen={itemID=12345,quantity=1,name="Weathered Explorer's Boots",icon=123456},
            automatic={{itemID=5678,quantity=2,name='Supply token'}},xp=1200,money=5600,status='observed',choiceStatus='observed',otherRewards='not captured'},
            {mapID=101,x=2710,y=7740,zone='Northern Stranglethorn',subzone='Booty Bay',level=24},1800000100)
        completedBytes=diskSize(db.events[2])
        j:Discover('atlas','p123','Forgotten cave','Interface\\\\Icons\\\\INV_Misc_Map03','atlas:original-character:p123')
        linkedBytes=diskSize(db.events[3]);eventStoreBytes=diskSize({events=db.events,quests=db.quests,seen=db.seen})
        j:Append('flight','Flight from Sentinel Hill',nil,
            {mapID=1436,x=5650,y=5260,zone='Westfall',subzone='Sentinel Hill',level=24},1800000200)
        flightBytes=diskSize(db.events[4])
        contrastBytes=diskSize({trailContrast=0.75})-diskSize({})
    ''')
    return results,{key:lua.globals()[key] for key in ['acceptedBytes','completedBytes','linkedBytes','eventStoreBytes','flightBytes','contrastBytes']}


def report(results,events):
    lines=['# Adventurer\'s Annals — measured storage', '',
           'Generated by `tests/annals_storage.py` using the shipping Lua 5.1 sampler and codec. Synthetic six-hour paths; these are scenario projections, not measured player behaviour.', '',
           'The fixtures use the current instance/death context (`false:false` outdoors and alive), hourly loading breaks and changing synthetic map IDs. They exercise the sampler directly, without live flight events or native world-coordinate conversion. Optional chunk join references are counted when produced; validated cross-map flight joins are covered by functional tests, not simulated here. Previous-prototype rows replay its retention thresholds through the current implementation, rather than running an archived build.', '',
           '## Six-hour measurements', '',
           '| Scenario | Retained points | Segments | Payload bytes | Estimated SV bytes | Effective SV bytes/point |',
           '|---|---:|---:|---:|---:|---:|']
    for r in results:
        lines.append(f"| {r['label']} | {r['points']:,} | {r['segments']:,} | {r['payload']:,} | {r['saved']:,} | {r['saved']/r['points']:.2f} |")
    lines+=['','Payload is exactly **9 ASCII bytes per retained point**. No escaping is needed. The SavedVariables estimator includes explicit numeric indices, quoted keys/strings, indentation, braces and commas; actual client whitespace may differ. Runtime Lua heap use is additional and is not predicted by disk bytes. Empty root/other Annals indexes are excluded from the trail table.', '',
            '## Projections', '',
            'Cells are **compact point payload / estimated trail SavedVariables MiB**. Projected SV adds two bytes per segment for growth of segment indices. No extra simplification is assumed after the fixture closes.', '',
            '| Scenario | 100 hours | 1,000 hours | 3,000 hours | 7,200 hours / 300 days |',
            '|---|---:|---:|---:|---:|']
    for r in results[1:4]:
        vals=[f"{r['payload']*h/r['hours']/1048576:.2f} / {(r['saved']+2*r['segments'])*h/r['hours']/1048576:.2f}" for h in (100,1000,3000,7200)]
        lines.append('| '+r['label']+' | '+' | '.join(vals)+' |')
    base=results[1];raw=results[4]
    lines+=['',f"Default continuous segment/header overhead in this fixture: **{base['saved']-base['payload']:,} bytes total**, approximately **{(base['saved']-base['payload'])/base['segments']:.1f} bytes/segment**.",
            f"Simplification reduced continuous retained points from **{raw['points']:,} to {base['points']:,}** ({100*(1-base['points']/raw['points']):.1f}%). The timing guard deliberately retains points on long straight stretches.", '',
            f"Compared with the previous prototype settings on the same fixtures, balanced recording reduces continuous points by **{100*(1-base['points']/results[5]['points']):.1f}%** and tight-turn points by **{100*(1-results[3]['points']/results[6]['points']):.1f}%**. Existing recorded history is not rewritten.", '',
            'Ordinary retained points are at least 15 seconds apart (normally 16 with the two-second ticker). At the conservative 15-second limit, 300 days of continuous travel would contribute 1,728,000 ordinary points / **14.83 MiB payload**, before headers and simplification. Event and stop/resume anchors, segment starts/endpoints and loading/map boundaries are exceptions; this is not a total storage cap. Combat skips simplification but still obeys the ordinary cadence limit.', '',
            '## Durable history, separately', '',
            f"- Representative acceptance: **{events['acceptedBytes']} estimated serialized bytes**.",
            f"- Completion with chosen item, automatic item, XP and copper: **{events['completedBytes']} bytes**.",
            f"- Linked Atlas discovery with historical name/icon/identity: **{events['linkedBytes']} bytes**.",
            f"- Representative confirmed flight departure with historical name/location: **{events['flightBytes']} bytes**, separate from breadcrumb payload and excluded from the three-event mix below.",
            f"- The three-event fixture including quest state and discovery deduplication indexes: **{events['eventStoreBytes']} bytes**."]
    average=events['eventStoreBytes']/3
    lines += [f"- At that fixture's composition, 20,000 events plus indexes: **{average*20000/1048576:.2f} MiB**; 100,000: **{average*100000/1048576:.2f} MiB**. Event frequency is independent of `/played`; these are counts, not assumed rates.", '',
              'Quest/title and discovery metadata are snapshots. Events have no age/count eviction. Point fidelity is the adjustable part. Whole backups duplicate captured data and have their existing 256 MiB portable bound; retained backup archives are additional disk use.', '',
              '## Sampling and policy', '',
              '- Check position every two seconds, with no per-frame history writes. Ordinary points must be at least 15 seconds apart and at least 40/10,000 map units (0.4%) from the previous retained point. Retain at 160 units (1.6%) displacement or 60 elapsed seconds. A bend deviating at least 40 units can preserve the preceding candidate, subject to the same minimum distance and cadence. The 60 seconds is elapsed time since the last retained point, not accumulated travel; stationary players do not produce periodic points. Event locations remain anchors.',
              '- A constant position produces one initial point, even across hours. Once movement pauses at exactly the same recorded coordinates for four seconds, retain its arrival as an anchor; on departure retain the last stationary timestamp as another anchor. These are boundary writes, with no periodic idle samples. An event at that position may intentionally add an anchor. New sessions retain a separate starting point.',
              '- Keep continuous flight paths through subzone-name and mounting changes. Break on loading/session boundaries, death/release, level changes, instance/death state, observed gaps over 12 seconds, backward time, or same-map jumps over 1,000 normalized units. Exact map changes start a new chunk; a join reference is saved only when adjacent observations have validated world positions on the same continent at most 1,000 yards apart. Normal chunk rotations may also join. Missing observations never gain a join.',
              '- Each segment has version, map ID, Unix start/finish seconds, start level, boundary reason, instance/death context and a printable data string, plus an optional `joinFrom` segment index. Each point encodes x(3 base64 digits), y(3), delta-seconds(2, maximum 4,095 seconds), anchor flag(1). Chunks hold at most 256 points; moving chunks rotate after 30 minutes. Closing may keep a pending endpoint at least four normalized units from the last retained point if it fits. Unknown formats or malformed chunks are preserved and skipped.',
              '- Completed chunks use iterative Ramer–Douglas–Peucker simplification with 30-unit spatial and time-interpolation error tolerances, mandatory event/stop/resume anchors and endpoints, and a maximum 120-second simplified chord where intermediate samples exist. Straight-line speed changes are retained when their timestamp-based positional error exceeds tolerance. Combat skips simplification for that chunk. There is no scheduled full-history simplification or silent deletion.',
              '- The live chunk is always a decodable saved string. Reload begins a fresh segment. Pending candidate coordinates are deliberately expendable; durable markers keep their own position.',
              '- Confirmed flight departures append durable events with flight-master icons. Opening or cancelling a taxi map does not create a departure; reloading already in flight does not invent one. Event capture continues with breadcrumb recording disabled. Flight events can add protected trail anchors while recording is enabled.', '',
              '## Projection, draw limits and age gradient', '',
              '- Range/map selection builds a metadata index, including descendant maps with validated map rectangles. Direct child-to-ancestor rectangles are preferred; otherwise immediate-parent rectangles are composed. Projection changes display coordinates only and never duplicates saved points for continent/world maps.',
              '- Scrubbing decodes at most 64 nearby chunks and keeps a 64-chunk cache. One following chunk may occupy a slot to interpolate a validated boundary connection. Arrow and partial-edge positions are display-only linear estimates between connected samples; gaps hold the last observation. The arrow updates every playback frame from cached endpoints while full route rendering remains throttled to ten updates per second, with immediate updates at sample/event boundaries. A bounded ring retains the newest 2,048 edges when these chunks exceed the draw budget; edges are then sorted chronologically for drawing. There are at most 512 recent event inputs and 192 grouped Atlas pins. Dense views disclose truncation; scrubbing earlier or narrowing dates exposes older geometry. These limits never delete history.',
              '- A saved `joinFrom` is drawn only when both endpoints are present in the selected view, in chronological order and at most 12 seconds apart. This preserves real loading/observation gaps and prevents a display-only projection from inventing connectivity.',
              '- Line age is measured from its destination timestamp to the clamped scrubber time: `age = max(0, scrubberTime - line.to.at)`. Heat is `2^(-age / 1800)`, giving a 30-minute half-life. With contrast `s`, cooling is `(1 - heat) * s`; RGBA is `(1 - 0.75*cooling, 0.82 - 0.27*cooling, 0.14 + 0.86*cooling, 0.8 - 0.68*cooling)`. Recent lines stay warm gold; older lines cool toward blue and fade. At maximum contrast the limiting alpha is 0.12, so age never hides a line entirely.',
              '- Trail age contrast ranges from 0% (uniform gold at alpha 0.8) to 100% (strongest effect), in 5% steps, defaulting to 75%. The setting is stored once per character as `settings.trailContrast`; an absent setting uses the default without a write. Markers retain their normal colors. Scrubbing into the past makes travel recent to that historical time warm again.',
              f"- Setting contrast to 75% adds **{events['contrastBytes']} estimated serialized bytes** to an otherwise empty settings table. No color, opacity, heat or projected coordinates are stored per point or segment. The gradient and composite native ?! tab icon therefore add no trail payload. The trail-only projection tables exclude settings and durable events.", '',
              '## What to tune after in-game testing', '',
              'Measure normalized thresholds on large zones and micro maps, flight-path bends, boat movement and short teleports. A sub-two-second teleport under the jump threshold with no loading event cannot reliably be distinguished from travel. Consider map-size-aware thresholds, time-block archival indexes, and a measured second-stage old-chunk simplifier preserving event anchors; do not introduce an arbitrary age limit.', '']
    return '\n'.join(lines)


if __name__=='__main__':
    results,events=measurements()
    text=report(results,events)
    if '--write' in sys.argv:
        path=Path(__file__).with_name('ANNALS_STORAGE.md');path.write_text(text,encoding='utf-8');print(text)
    else:
        print(text)
